### ISSUE TITLE
Unicode decode error 

### ISSUE THREAD

**Issue by pratik-choudhari** [gahjelle/pythonji#1]
I tried to execute the example provided in this repository, but I got

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 19: character maps to <undefined>`

Versions:
Windows 10
Python 3.8.10
Pythonji 0.1.1

**Comment by pavelzw** [comment]
I fixed it in a fork of mine as this repo doesn't seem maintained anymore. `pip install pythonji-2` should fix it.

**Comment by pratik-choudhari** [comment]
Awesome
